dpf:
  ingestion:
    directory: /dpf/ingestion/incoming_dir
    queue: incoming_file_queue
    config-folder: /dpf/ingestion/config
  process:
    queue: process_queue
    config-folder: /dpf/process/config
    shared-folder: /dpf/process/shared
  catalogue:
    url: couchdb:5984/
    username: admin
    password: password
  archive:
    directory: /dpf/archive