dpf:
  ingestion:
    directory: ${HOME}/dpf/ingestion/incoming_dir
    queue: incoming_file_queue
    config-folder: ${HOME}/dpf/ingestion/config
  process:
    queue: process_queue
    config-folder: ${HOME}/dpf/process/config
  catalogue:
    url: http://127.0.0.1:5984/
    username: admin
    password: password
  archive:
    directory: ${HOME}/dpf/archive/